name: smart_parking
description: Smart Parking Management System - Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.0
  
  # HTTP & API
  http: ^1.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3

  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  
  # Image
  image_picker: ^1.0.5
  
  # Date & Time
  intl: ^0.18.1
  
  # Icons
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
